DGN21/Controllers/AbogadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DGN21.Controllers
{
    [Authorize(Roles = "ABOGADO(A)")]
    public class AbogadoController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

DGN21/Controllers/AdminController.cs
using DGN21.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DGN21.Controllers
{
    [Authorize(Roles = "ADMINISTRADOR")]
    public class AdminController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        readonly ApplicationDbContext db = new ApplicationDbContext();

        public AdminController()
        {
        }

        public AdminController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Usuarios()
        {
            return View();
        }

        public ActionResult NotFound()
        {
            ModelState.AddModelError(string.Empty, "No se encontró solicitud con ese folio, verifique el número en su correo de confirmación de la solicitud.");

            return View("Usuarios");
        }

        [HttpPost]
        public ActionResult Usuario(ApplicationUser model)
        {
            ViewBag.Roles = db.Roles.ToList();
            try
            {
                if (!ModelState.IsValid)
                {
                    throw new Exception("Correo Inválido.");
                }

                ApplicationUser user = UserManager.FindByEmail(model.Email);
                if (user.Roles.Count > 0)
                {
                    user.PhoneNumber = user.Roles.FirstOrDefault().RoleId;
                }
                return View(user);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return RedirectToAction("NotFound", "Home");
        }

        [HttpPost]
        public ActionResult UsuarioRol(ApplicationUser model)
        {
            ViewBag.Roles = db.Roles.ToList();
            try
            {
                var idUsuario = model.Id;
                var rol = string.Empty;
                if (!string.IsNullOrEmpty(model.PhoneNumber))
                {
                    rol = db.Roles.Where(x=>x.Id == model.PhoneNumber).FirstOrDefault().Name;
                }

                ApplicationUser user = UserManager.FindById(idUsuario);
                if (user.Roles.Count > 0)
                {
                    var roleAnterior = user.Roles.FirstOrDefault().RoleId;
                    var roleNameAnterior = db.Roles.Where(x => x.Id == roleAnterior).FirstOrDefault().Name;
                    UserManager.RemoveFromRole(idUsuario, roleNameAnterior);
                }
                UserManager.AddToRole(idUsuario, rol);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Usuario", model);
            }

            return RedirectToAction("Usuarios");
        }
    }
}

DGN21/Controllers/ArchivoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DGN21.Controllers
{
    [Authorize(Roles = "ARCHIVO")]
    public class ArchivoController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

DGN21/Controllers/ContadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DGN21.Controllers
{
    [Authorize(Roles = "CONTADOR(A)")]
    public class ContadorController : Controller
    {
        // GET: Contador
        public ActionResult Index()
        {
            return View();
        }
    }
}

DGN21/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DGN21</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/img/favicon.ico" rel="icon" type="image/png" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="navbar navbar-red navbar-fixed-top">
        <div class="container" style="width: 100%!important;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Home")" class="navbar-brand"><img src="~/Content/img/logo_notarias.jpg" alt="Dirección General de Notarías" style="height: 50px; margin-top: -15px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Solicitar", "Solicitud", "Solicitudes")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="width: 85%!important;">
        @RenderBody()
        <hr />
        <footer class="copyright">
            <img src="~/Content/img/LogotipoGobiernoSonora_LogotipoColorTricromía.png" style="height:160px;margin-bottom: 10px;">
            <p>
                <b>Dirección General de Notarías del Estado de Sonora</b>
                Centro de Gobierno, Edif. Sonora Norte, Planta Baja, Paseo del Canal y Comonfort, C.P. 83280, Hermosillo, Sonora, México.
                <br /> Teléfono: (662) 217-45-90 y 217-03-14
                <a href="https://notarias.sonora.gob.mx/" title="Dirección General de Notarias" class="acolor3">notarias.sonora.gob.mx</a>
            </p>
            <p><small>&copy; Gobierno del Estado de Sonora. Todos los Derechos Reservados</small></p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr/toastr.min.js" asp-file-version="true"></script>
    <script src="~/Scripts/messageCommon.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

DGN21/Views/Shared/_LayoutAbogado.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DGN21</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/img/favicon.ico" rel="icon" type="image/png" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="navbar navbar-red navbar-fixed-top">
        <div class="container" style="width: 100%!important;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Abogado")" class="navbar-brand"><img src="~/Content/img/logo_notarias.jpg" alt="Dirección General de Notarías" style="height: 50px; margin-top: -15px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Solicitudes turnadas", "InboxTurnadas", "Solicitudes")</li>
                    <li>@Html.ActionLink("Reportes turnadas", "ReporteTurnadas", "Solicitudes")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="width: 85%!important;">
        @RenderBody()
        <hr />
        <footer class="copyright">
            <img src="~/Content/img/LogotipoGobiernoSonora_LogotipoColorTricromía.png" style="height:160px;margin-bottom: 10px;">
            <p>
                <b>Dirección General de Notarías del Estado de Sonora</b>
                Centro de Gobierno, Edif. Sonora Norte, Planta Baja, Paseo del Canal y Comonfort, C.P. 83280, Hermosillo, Sonora, México.
                <br /> Teléfono: (662) 217-45-90 y 217-03-14
                <a href="https://notarias.sonora.gob.mx/" title="Dirección General de Notarias" class="acolor3">notarias.sonora.gob.mx</a>
            </p>
            <p><small>&copy; Gobierno del Estado de Sonora. Todos los Derechos Reservados</small></p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr/toastr.min.js" asp-file-version="true"></script>
    <script src="~/Scripts/messageCommon.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

DGN21/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DGN21</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/img/favicon.ico" rel="icon" type="image/png" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="navbar navbar-red navbar-fixed-top">
        <div class="container" style="width: 100%!important;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Admin")" class="navbar-brand"><img src="~/Content/img/logo_notarias.jpg" alt="Dirección General de Notarías" style="height: 50px; margin-top: -15px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Generar Roles", "Usuarios", "Admin")</li>
                    <li>@Html.ActionLink("Solicitar", "Solicitud", "Solicitudes")</li>
                    <li>@Html.ActionLink("Solicitudes sin turnar", "InboxTurnar", "Solicitudes")</li>
                    <li>@Html.ActionLink("Solicitudes ya asignadas", "InboxAsignada", "Solicitudes")</li>
                    <li>@Html.ActionLink("Reporte mis solicitudes", "ReporteSolicitudes", "Solicitudes")</li>
                    <li>@Html.ActionLink("Reporte todas las solicitudes", "ReporteAllSolicitudes", "Solicitudes")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="width: 85%!important;">
        @RenderBody()
        <hr />
        <footer class="copyright">
            <img src="~/Content/img/LogotipoGobiernoSonora_LogotipoColorTricromía.png" style="height:160px;margin-bottom: 10px;">
            <p>
                <b>Dirección General de Notarías del Estado de Sonora</b>
                Centro de Gobierno, Edif. Sonora Norte, Planta Baja, Paseo del Canal y Comonfort, C.P. 83280, Hermosillo, Sonora, México.
                <br /> Teléfono: (662) 217-45-90 y 217-03-14
                <a href="https://notarias.sonora.gob.mx/" title="Dirección General de Notarias" class="acolor3">notarias.sonora.gob.mx</a>
            </p>
            <p><small>&copy; Gobierno del Estado de Sonora. Todos los Derechos Reservados</small></p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr/toastr.min.js" asp-file-version="true"></script>
    <script src="~/Scripts/messageCommon.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

DGN21/Views/Shared/_LayoutArchivo.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DGN21</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/img/favicon.ico" rel="icon" type="image/png" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="navbar navbar-red navbar-fixed-top">
        <div class="container" style="width: 100%!important;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Archivo")" class="navbar-brand"><img src="~/Content/img/logo_notarias.jpg" alt="Dirección General de Notarías" style="height: 50px; margin-top: -15px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Solicitudes turnadas", "InboxTurnadas", "Solicitudes")</li>
                    <li>@Html.ActionLink("Reportes turnadas", "ReporteTurnadas", "Solicitudes")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="width: 85%!important;">
        @RenderBody()
        <hr />
        <footer class="copyright">
            <img src="~/Content/img/LogotipoGobiernoSonora_LogotipoColorTricromía.png" style="height:160px;margin-bottom: 10px;">
            <p>
                <b>Dirección General de Notarías del Estado de Sonora</b>
                Centro de Gobierno, Edif. Sonora Norte, Planta Baja, Paseo del Canal y Comonfort, C.P. 83280, Hermosillo, Sonora, México.
                <br /> Teléfono: (662) 217-45-90 y 217-03-14
                <a href="https://notarias.sonora.gob.mx/" title="Dirección General de Notarias" class="acolor3">notarias.sonora.gob.mx</a>
            </p>
            <p><small>&copy; Gobierno del Estado de Sonora. Todos los Derechos Reservados</small></p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr/toastr.min.js" asp-file-version="true"></script>
    <script src="~/Scripts/messageCommon.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

DGN21/Views/Shared/_LayoutContador.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DGN21</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/img/favicon.ico" rel="icon" type="image/png" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="navbar navbar-red navbar-fixed-top">
        <div class="container" style="width: 100%!important;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Contador")" class="navbar-brand"><img src="~/Content/img/logo_notarias.jpg" alt="Dirección General de Notarías" style="height: 50px; margin-top: -15px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Reporte de solicitudes turnadas por usuario", "ReporteTurnadasUsuarios", "Solicitudes")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="width: 85%!important;">
        @RenderBody()
        <hr />
        <footer class="copyright">
            <img src="~/Content/img/LogotipoGobiernoSonora_LogotipoColorTricromía.png" style="height:160px;margin-bottom: 10px;">
            <p>
                <b>Dirección General de Notarías del Estado de Sonora</b>
                Centro de Gobierno, Edif. Sonora Norte, Planta Baja, Paseo del Canal y Comonfort, C.P. 83280, Hermosillo, Sonora, México.
                <br /> Teléfono: (662) 217-45-90 y 217-03-14
                <a href="https://notarias.sonora.gob.mx/" title="Dirección General de Notarias" class="acolor3">notarias.sonora.gob.mx</a>
            </p>
            <p><small>&copy; Gobierno del Estado de Sonora. Todos los Derechos Reservados</small></p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr/toastr.min.js" asp-file-version="true"></script>
    <script src="~/Scripts/messageCommon.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

DGN21/Views/Shared/_LayoutDirector.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DGN21</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/img/favicon.ico" rel="icon" type="image/png" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="navbar navbar-red navbar-fixed-top">
        <div class="container" style="width: 100%!important;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Contador")" class="navbar-brand"><img src="~/Content/img/logo_notarias.jpg" alt="Dirección General de Notarías" style="height: 50px; margin-top: -15px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Solicitudes sin turnar", "InboxTurnar", "Solicitudes")</li>
                    <li>@Html.ActionLink("Solicitudes ya asignadas", "InboxAsignada", "Solicitudes")</li>
                    <li>@Html.ActionLink("Reporte de solicitudes", "ReporteAllSolicitudes", "Solicitudes")</li>
                    <li>@Html.ActionLink("Reportes de correspondencia", "Reporte", "Correspondencia")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="width: 85%!important;">
        @RenderBody()
        <hr />
        <footer class="copyright">
            <img src="~/Content/img/LogotipoGobiernoSonora_LogotipoColorTricromía.png" style="height:160px;margin-bottom: 10px;">
            <p>
                <b>Dirección General de Notarías del Estado de Sonora</b>
                Centro de Gobierno, Edif. Sonora Norte, Planta Baja, Paseo del Canal y Comonfort, C.P. 83280, Hermosillo, Sonora, México.
                <br /> Teléfono: (662) 217-45-90 y 217-03-14
                <a href="https://notarias.sonora.gob.mx/" title="Dirección General de Notarias" class="acolor3">notarias.sonora.gob.mx</a>
            </p>
            <p><small>&copy; Gobierno del Estado de Sonora. Todos los Derechos Reservados</small></p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr/toastr.min.js" asp-file-version="true"></script>
    <script src="~/Scripts/messageCommon.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

DGN21/Views/Shared/_LayoutRecepcion.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DGN21</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/img/favicon.ico" rel="icon" type="image/png" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="navbar navbar-red navbar-fixed-top">
        <div class="container" style="width: 100%!important;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Recepcion")" class="navbar-brand"><img src="~/Content/img/logo_notarias.jpg" alt="Dirección General de Notarías" style="height: 50px; margin-top: -15px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Solicitar", "Solicitud", "Solicitudes")</li>
                    @*<li>@Html.ActionLink("Solicitudes sin turnar", "InboxTurnar", "Solicitudes")</li>*@
                    @*<li>@Html.ActionLink("Solicitudes ya asignadas", "InboxAsignada", "Solicitudes")</li>*@
                    <li>@Html.ActionLink("Reporte mis solicitudes", "ReporteSolicitudes", "Solicitudes")</li>
                    <li>@Html.ActionLink("Correspondencia", "Nueva", "Correspondencia")</li>
                    <li>@Html.ActionLink("Bandeja de correspondencia", "Inbox", "Correspondencia")</li>
                    <li>@Html.ActionLink("Reportes de correspondencia", "Reporte", "Correspondencia")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="width: 85%!important;">
        @RenderBody()
        <hr />
        <footer class="copyright">
            <img src="~/Content/img/LogotipoGobiernoSonora_LogotipoColorTricromía.png" style="height:160px;margin-bottom: 10px;">
            <p>
                <b>Dirección General de Notarías del Estado de Sonora</b>
                Centro de Gobierno, Edif. Sonora Norte, Planta Baja, Paseo del Canal y Comonfort, C.P. 83280, Hermosillo, Sonora, México.
                <br /> Teléfono: (662) 217-45-90 y 217-03-14
                <a href="https://notarias.sonora.gob.mx/" title="Dirección General de Notarias" class="acolor3">notarias.sonora.gob.mx</a>
            </p>
            <p><small>&copy; Gobierno del Estado de Sonora. Todos los Derechos Reservados</small></p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr/toastr.min.js" asp-file-version="true"></script>
    <script src="~/Scripts/messageCommon.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

DGN21/Views/Shared/_LayoutSecretaria.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DGN21</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/img/favicon.ico" rel="icon" type="image/png" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="navbar navbar-red navbar-fixed-top">
        <div class="container" style="width: 100%!important;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Secretaria")" class="navbar-brand"><img src="~/Content/img/logo_notarias.jpg" alt="Dirección General de Notarías" style="height: 50px; margin-top: -15px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Solicitar", "Solicitud", "Solicitudes")</li>
                    <li>@Html.ActionLink("Solicitudes sin turnar", "InboxTurnar", "Solicitudes")</li>
                    <li>@Html.ActionLink("Solicitudes ya asignadas", "InboxAsignada", "Solicitudes")</li>
                    <li>@Html.ActionLink("Reporte mis solicitudes", "ReporteSolicitudes", "Solicitudes")</li>
                    <li>@Html.ActionLink("Reporte de solicitudes", "ReporteAllSolicitudes", "Solicitudes")</li>
                    <li>@Html.ActionLink("Correspondencia", "Nueva", "Correspondencia")</li>
                    <li>@Html.ActionLink("Bandeja de correspondencia", "Inbox", "Correspondencia")</li>
                    <li>@Html.ActionLink("Reportes de correspondencia", "Reporte", "Correspondencia")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="width: 85%!important;">
        @RenderBody()
        <hr />
        <footer class="copyright">
            <img src="~/Content/img/LogotipoGobiernoSonora_LogotipoColorTricromía.png" style="height:160px;margin-bottom: 10px;">
            <p>
                <b>Dirección General de Notarías del Estado de Sonora</b>
                Centro de Gobierno, Edif. Sonora Norte, Planta Baja, Paseo del Canal y Comonfort, C.P. 83280, Hermosillo, Sonora, México.
                <br /> Teléfono: (662) 217-45-90 y 217-03-14
                <a href="https://notarias.sonora.gob.mx/" title="Dirección General de Notarias" class="acolor3">notarias.sonora.gob.mx</a>
            </p>
            <p><small>&copy; Gobierno del Estado de Sonora. Todos los Derechos Reservados</small></p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr/toastr.min.js" asp-file-version="true"></script>
    <script src="~/Scripts/messageCommon.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>