DGN21/Models/ViewModels/CorrespondenciaViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DGN21.Models.ViewModels
{
    public class CorrespondenciaViewModels
    {
        public CorrespondenciaViewModels()
        {
        }

        public CorrespondenciaModels Correspondencia { get; set; }

        public FiltroReporteModels FiltroReporte { get; set; }

        public List<CorrespondenciaModels> CorrespondenciaInbox { get; set; }
    }
}

DGN21/Controllers/CorrespondenciaController.cs
using DGN21.Models;
using DGN21.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DGN21.Controllers
{    
    public class CorrespondenciaController : Controller
    {
        readonly ApplicationDbContext db = new ApplicationDbContext();

        [Authorize(Roles = "RECEPCION,SECRETARIA(O)")]
        public ActionResult Nueva(int id = 0)
        {
            if(id.Equals(0))
            {
                return View(new CorrespondenciaModels());
            }
            else
            {
                var correspondecia = db.Correspondencia.Where(x => x.IdCorrespondencia == id).FirstOrDefault();
                return View(correspondecia);
            }
        }

        [Authorize(Roles = "RECEPCION,SECRETARIA(O)")]
        [HttpPost]
        public ActionResult Guardar(CorrespondenciaModels correspondencia)
        {
            try
            {
                if (ModelState.ContainsKey("IdCorrespondencia"))
                    ModelState["IdCorrespondencia"].Errors.Clear();
                if (!ModelState.IsValid)
                {
                    return View("Nueva", correspondencia);
                }

                if (correspondencia.IdCorrespondencia.Equals(0))
                {
                    correspondencia.IdUserCreacion = User.Identity.GetUserId();
                    db.Correspondencia.Add(correspondencia);
                }
                else
                {
                    db.Entry(correspondencia).State = EntityState.Modified;
                }

                db.SaveChanges();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            
            return RedirectToAction("Nueva", new { id = correspondencia.IdCorrespondencia });
        }

        [Authorize(Roles = "RECEPCION,SECRETARIA(O)")]
        public ActionResult Inbox()
        {
            var correspondencia = db.Correspondencia.OrderByDescending(x=>x.IdCorrespondencia).ToList();
            return View(correspondencia);
        }

        [Authorize(Roles = "RECEPCION,DIRECTOR(A),SECRETARIA(O)")]
        public ActionResult Reporte()
        {
            var solicitudes = new List<SolicitudesModels>();
            var allSolicitudes = db.Solicitudes.ToList();
            CorrespondenciaViewModels correspondenciaViewModels = new CorrespondenciaViewModels();
            correspondenciaViewModels.CorrespondenciaInbox = db.Correspondencia.ToList();

            return View(correspondenciaViewModels);
        }

        [Authorize(Roles = "RECEPCION,DIRECTOR(A),SECRETARIA(O)")]
        [HttpPost]
        public ActionResult Reporte(FiltroReporteModels filtroReporte)
        {
            filtroReporte.FechaFinReporte = new DateTime(filtroReporte.FechaFinReporte.Value.Year, filtroReporte.FechaFinReporte.Value.Month, filtroReporte.FechaFinReporte.Value.Day, 23, 59, 59, 999);
            var correspondenciaInbox = new List<CorrespondenciaModels>();
            if (filtroReporte.FechaInicioReporte == null && filtroReporte.FechaFinReporte == null)
            {
                correspondenciaInbox = db.Correspondencia.ToList();
            }
            else if (filtroReporte.FechaInicioReporte != null && filtroReporte.FechaFinReporte != null)
            {
                correspondenciaInbox = db.Correspondencia.Where(x=> x.FechaCreacion >= filtroReporte.FechaInicioReporte && x.FechaCreacion <= filtroReporte.FechaFinReporte).ToList();
            }
            else if (filtroReporte.FechaInicioReporte != null && filtroReporte.FechaFinReporte == null)
            {
                correspondenciaInbox = db.Correspondencia.Where(x => x.FechaCreacion > filtroReporte.FechaInicioReporte).ToList();
            }
            else if (filtroReporte.FechaInicioReporte == null && filtroReporte.FechaFinReporte != null)
            {
                correspondenciaInbox = db.Correspondencia.Where(x => x.FechaCreacion < filtroReporte.FechaFinReporte).ToList();
            }

            CorrespondenciaViewModels correspondenciaViewModels = new CorrespondenciaViewModels();
            correspondenciaViewModels.FiltroReporte = filtroReporte;
            correspondenciaViewModels.CorrespondenciaInbox = correspondenciaInbox;

            return View("Reporte", correspondenciaViewModels);
        }
    }
}

DGN21/Views/Correspondencia/Inbox.cshtml
@model List<DGN21.Models.CorrespondenciaModels>
@{
    ViewBag.Title = "Bandeja de correspondencia";
    if(User.IsInRole("RECEPCION"))
    {
        Layout = "~/Views/Shared/_LayoutRecepcion.cshtml";
    }
    else if (User.IsInRole("SECRETARIA(O)"))
    {
        Layout = "~/Views/Shared/_LayoutSecretaria.cshtml";
    }
}
@section styles {
    <link rel="stylesheet" type="text/css" href="~/Content/DataTables/media/css/dataTables.bootstrap.css">
}
<h2>@ViewBag.Title</h2>
<br />
<div class="light-bordered-rigth">
    <div class="row">
        <div class="col-xs-12">
            <table id="datatable1" class="table table-striped table-bordered" style="width:100%;">
                <thead>
                    <tr>
                        <th style="text-align:center">FOLIO</th>
                        <th style="text-align:center">NO. OFICIO</th>
                        <th style="text-align:center">DESTINATARIO</th>
                        <th style="text-align:center">REMITENTE</th>
                        <th style="text-align:center">DEPENDENCIA</th>
                        <th style="text-align:center">ASUNTO</th>
                        <th style="text-align:center">FECHA DE OFICIO</th>
                        <th style="text-align:center">FECHA DE RECIBIDO</th>
                        <th style="text-align:center">FECHA DE TÉRMINO</th>
                        <th style="text-align:center">ALERTA DE TÉRMINO</th>
                        <th style="text-align:center">FECHA DE REGISTRO</th>
                        <th class="no-sort"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.IdCorrespondencia)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NoOficio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Destinatario)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Remitente)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Dependencia)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Asunto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaOficio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaRecibido)
                        </td>
                        <td>
                            @if (item.FechaTermino != new DateTime(1900, 01, 01))
                            {
                                @Html.DisplayFor(modelItem => item.FechaTermino)
                            }
                        </td>

                        <td>
                            @if ((item.FechaTermino.Date >= DateTime.Now.Date) && (item.FechaTermino.Date <= DateTime.Now.AddDays(3).Date))
                            {
                                <p style="background:red; color:white; font-weight:bold;">&nbsp;</p>
                            }
                            else if ((item.FechaTermino.Date >= DateTime.Now.Date) && (item.FechaTermino.Date <= DateTime.Now.AddDays(5).Date))
                            {
                                <p style="background:yellow; color:white; font-weight:bold;">&nbsp;</p>
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaCreacion)
                        </td>
                        <td>
                            <button id="detalle" type="button" class="btn btn-info btn-xs" title="Modificar" onclick="location.href='@Url.Action("Nueva", "Correspondencia", new { id = item.IdCorrespondencia })'">
                                <i class="glyphicon glyphicon-edit"></i>
                            </button>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.2/jspdf.plugin.autotable.js"></script>
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables/media/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables/media/js/dataTables.bootstrap.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable1').DataTable({
                "order": [[9, "desc"], [8, "asc"]],
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "Sin solicitudes",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Sin información",
                    "infoFiltered": "(Filtrado de _MAX_ registros totales)",
                    "paginate": {
                        "previous": "Anterior",
                        "next": "Siguiente",
                        "first": "Primera página",
                        "last": "Última página"
                    },
                    "sSearch": "Buscar:"
                },
                "columnDefs": [{
                    "targets": 'no-sort',
                    "orderable": false,
                }]
            });
        });
    </script>
}

DGN21/Views/Correspondencia/Nueva.cshtml
@model DGN21.Models.CorrespondenciaModels
@{
    ViewBag.Title = "Nueva Correspondencia";
    ViewBag.Message = "LLenar datos de correspondencia";
    if(User.IsInRole("RECEPCION"))
    {
        Layout = "~/Views/Shared/_LayoutRecepcion.cshtml";
    }
    else if (User.IsInRole("SECRETARIA(O)"))
    {
        Layout = "~/Views/Shared/_LayoutSecretaria.cshtml";
    }
}
@section Styles {
    <link href="//www.fuelcdn.com/fuelux/3.13.0/css/fuelux.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/Content/DataTables/media/css/dataTables.bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.0.1/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="~/Content/bootstrap-datepicker3.min.css" />
}
<h2>@ViewBag.Title</h2>
<br />
<div class="row">
    <div class="fuelux col-xs-12">
        @using (Html.BeginForm("Guardar", "Correspondencia", FormMethod.Post, new { id = "frmCorrespondencia" }))
        {
            <div class="wizard" data-initialize="wizard" id="myWizard">
                <div class="steps-container">
                    <ul class="steps">
                        <li data-step="1" class="active">
                            <span class="badge">1</span>@ViewBag.Message
                            <span class="chevron"></span>
                        </li>
                    </ul>
                </div>
                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="alert alert-danger">
                        @Html.ValidationSummary(false, "Debe ingresar toda la información requerida.", new { @class = "text-danger" })
                    </div>
                }
                <div class="step-content">
                    <div class="step-pane active sample-pane alert" data-step="1">
                        @Html.HiddenFor(model => model.IdCorrespondencia, new { @class = "form-control", @Id = "hdIdCorrespondencia" })
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.NoOficio, new { @class = "control-label", @id = "lblNoOficio" })
                                    @Html.TextBoxFor(model => model.NoOficio, new { @class = "form-control", @Id = "txtNoOficio" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Destinatario, new { @class = "control-label", @id = "lblDestinatario" })
                                    @Html.TextBoxFor(model => model.Destinatario, new { @class = "form-control", @Id = "txtDestinatario" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Remitente, new { @class = "control-label", @id = "lblRemitente" })
                                    @Html.TextBoxFor(model => model.Remitente, new { @class = "form-control", @Id = "txtRemitente" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Dependencia, new { @class = "control-label", @id = "lblDependencia" })
                                    @Html.TextBoxFor(model => model.Dependencia, new { @class = "form-control", @Id = "txtDependencia" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Asunto, new { @class = "control-label", @id = "lblAsunto" })
                                    @Html.TextBoxFor(model => model.Asunto, new { @class = "form-control", @Id = "txtAsunto" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-2">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FechaOficio, new { @Id = "lblFechaOficio", @class = "control-label" })
                                    <div class="input-group date">
                                        <div class="input-group-addon">
                                            <i class="glyphicon glyphicon-calendar"></i>
                                        </div>
                                        @Html.TextBoxFor(model => model.FechaOficio, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right datepicker", @Id = "txtFechaOficio" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-2">
                                <div class="form-group">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-2">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FechaRecibido, new { @Id = "lblFechaRecibido", @class = "control-label" })
                                    <div class="input-group date">
                                        <div class="input-group-addon">
                                            <i class="glyphicon glyphicon-calendar"></i>
                                        </div>
                                        @Html.TextBoxFor(model => model.FechaRecibido, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right datepicker", @Id = "txtFechaRecibido" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-2">
                                <div class="form-group">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-2">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FechaTermino, new { @Id = "lblFechaTermino", @class = "control-label" })
                                    <div class="input-group date">
                                        <div class="input-group-addon">
                                            <i class="glyphicon glyphicon-calendar"></i>
                                        </div>
                                        @Html.TextBoxFor(model => model.FechaTermino, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right datepicker", @Id = "txtFechaTermino" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pull-right">
                            <button id="submit" type="submit" class="btn btn-success">
                                <i class="glyphicon glyphicon-floppy-save"></i> Guardar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@section Scripts {
    <script src="//www.fuelcdn.com/fuelux/3.13.0/js/fuelux.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.2/jspdf.plugin.autotable.js"></script>
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables/media/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables/media/js/dataTables.bootstrap.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.0.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var objMessageCommon = new MessageCommon();
            var onErrorGetInfo = function (error) {
                objMessageCommon.errorTitle("Ocurrió un error al consultar la información.", "Error");
            }

            var fechaO = $("#txtFechaOficio").val();
            if (fechaO === "01/01/0001") {
                $("#txtFechaOficio").val("");
            }

            var fechaR = $("#txtFechaRecibido").val();
            if (fechaR === "01/01/0001") {
                $("#txtFechaRecibido").val("");
            }

            var fechaT = $("#txtFechaTermino").val();
            if (fechaT === "01/01/0001") {
                $("#txtFechaTermino").val("");
            }

            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                defaultDate: moment(new Date())
            });

            $('#frmCorrespondencia').submit(function () {
                //Validation/
                if ($('#txtFechaOficio').val().trim() == "") {
                    objMessageCommon.warningTitle("Debes seleccionar la fecha de oficio.", "Información Incompleta");
                    return false;
                }
                if ($('#txtFechaRecibido').val().trim() == "") {
                    objMessageCommon.warningTitle("Debes seleccionar la fecha de recibido.", "Información Incompleta");
                    return false;
                }
                if ($('#txtFechaTermino').val().trim() == "") {
                    objMessageCommon.warningTitle("Debes seleccionar la fecha de término.", "Información Incompleta");
                    return false;
                }
            })            
        });
    </script>
}