DGN21/Models/ViewModels/SolicitudesViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DGN21.Models.ViewModels
{
    public class SolicitudesViewModels
    {
        public SolicitudesViewModels()
        {
        }

        public SolicitudesModels Solicitud { get; set; }

        public SolicitudesBusquedaModels SolicitudBusqueda { get; set; }

        public TurnadosModels Turnada { get; set; }

        [Display(Name = "Papeleta de pago")]
        public PapeletasPagoModels PapeletasPago { get; set; }

        public ObservacionesSolicitudesModels Observacion { get; set; }

        public List<SolicitudesModels> Solicitudes { get; set; }

        public List<ObservacionesSolicitudesModels> Observaciones { get; set; }

        public List<SolicitudInbox> SolicitudesInbox = new List<SolicitudInbox>();

        public FiltroReporteModels FiltroReporte = new FiltroReporteModels();

        public class SolicitudInbox
        {            
            public SolicitudesModels Solicitud { get; set; }

            [Display(Name = "Papeleta de pago")]
            public PapeletasPagoModels PapeletasPago { get; set; }

            public ObservacionesSolicitudesModels Observacion { get; set; }

            public TurnadosModels Turnada { get; set; }

            public List<ObservacionesSolicitudesModels> ObservacionesUltimoTurnado { get; set; }
        }
    }
}

DGN21/Controllers/SolicitudesController.cs
using DGN21.Models;
using DGN21.Models.ViewModels;
using Microsoft.AspNet.Identity;
using reCAPTCHA.MVC;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace DGN21.Controllers
{
    public class SolicitudesController : Controller
    {
        readonly ApplicationDbContext db = new ApplicationDbContext();

        readonly string avisoPrivacidad = "<br/><br/><br/><strong><p>AVISO DE PRIVACIDAD SIMPLIFICADO</p><p>I. Denominación del Responsable:</p><p style='color: #833C0B;'>Dirección General de Notarías</p></strong><p>Los datos personales recabados por esta Dirección, dependiente de la Secretaría de Gobierno del Estado de Sonora, serán protegidos, incorporados y tratados de conformidad con lo previsto en la Ley General de Protección de Datos Personales en Posesión de Sujetos Obligados y la Ley de Protección de Datos Personales en Posesión de Sujetos Obligados del Estado de Sonora y demás normatividad que resulte aplicable.</p>"
            + "<strong><p>II. La finalidad del tratamiento de sus datos personales es:</p></strong><p>Los datos personales otorgados a esta Dirección, serán utilizados única y exclusivamente para brindar la atención y respuesta a la solicitud de algún trámite y/o servicio, y serán resguardados por el personal responsable del trámite o servicio en cuestión. Todos los servicios y trámites que ofrece la Dirección serán entregados a las personas que intervengan o acrediten interés jurídico en la escritura que obre en los Archivos de la Dirección General de Notarías.</p>"
            + "<strong><p>III. De las Transferencias:</p></strong><p>Se hace de su conocimiento que sus datos personales podrán ser transmitidos a otras autoridades siempre y cuando los datos se utilicen para el ejercicio de facultades propias de las mismas, además de otras transmisiones previstas en la Ley.</p>"
            + "<strong><p>IV. Mecanismos y medios disponibles para que el Titular de los datos personales pueda manifestar su negativa para el tratamiento de sus datos personales.</p></strong><p>La Secretaría de Gobierno a través de las unidades administrativas de su adscripción ante las cuales se proporcionen datos personales, pondrá a consideración del ciudadano, a través de un manifiesto expreso, la autorización o no de la transferencia de sus datos personales a otras autoridades, cuyo tratamiento sea susceptible de transferencia. Conforme al Art. 120 fracción VIII de la Ley del Notariado para el Estado de Sonora.</p>"
            + "<strong><p>V. El aviso de privacidad integral podrá ser consultado en las siguientes páginas electrónicas:</p></strong><p><a href='https://notarias.sonora.gob.mx/'>notarias.sonora.gob.mx</a><br/><a href='https://notarias.sonora.gob.mx/conocenos/aviso-de-privacidad.html'>notarias.sonora.gob.mx/conocenos/aviso-de-privacidad.html</a></p>";

        public enum TipoTramite : int { CopiaSimple = 1, CopiaCertificada = 2, Testimonio = 3, DispTestamentaria = 4, BusquedaAnio = 5, TerminacionEsc = 6, Otros = 7 };

        // GET: Solicitudes
        public ActionResult Solicitud()
        {
            ViewBag.TiposTramite = db.TiposTramites.ToList();

            return View(new SolicitudesModels());
        }

        public ActionResult Folio(int id = 0)
        {
            if (!id.Equals(0))
            {
                SolicitudesModels solicitud = db.Solicitudes.Where(x => x.IdSolicitud == id).FirstOrDefault();
                solicitud.Documentos = db.Documentos.Where(x => x.IdSolicitud == id).ToList();
                return View(solicitud);
            }

            return View(new SolicitudesModels());
        }

        public bool EnviarCorreoSolicitud(int idSolicitud)
        {
            var envio = false;
            SolicitudesModels solicitud = db.Solicitudes.Where(x => x.IdSolicitud == idSolicitud).FirstOrDefault();

            var body = "<p>Estimado(a) Ciudadano(a) {0} {1}</p><p>Su solicitud se registró con éxito, con el folio siguiente: {2}</p><br/><p>Para seguimiento de su solicitud ingrese con su folio a <a href='http://tramitesdgn.sonora.gob.mx/'>tramitesdgn.sonora.gob.mx</a></p>";
            body += avisoPrivacidad;
            var message = new MailMessage();
            message.To.Add(new MailAddress(solicitud.CorreoElectronico));  // replace with valid value 
            message.From = new MailAddress("dgnsonora@sonora.gob.mx", "DIRECCION GENERAL DE NOTARIAS");  // replace with valid value
            message.Subject = "Confirmación de solicitud";
            message.Body = string.Format(body, solicitud.NombreSolicitante, solicitud.ApellidoPaterno, solicitud.IdSolicitud);
            message.IsBodyHtml = true;

            using (var smtp = new SmtpClient())
            {
                var credential = new NetworkCredential
                {
                    UserName = "dgnsonora@sonora.gob.mx",  // replace with valid value
                    Password = "NOTARIASSON2020*"  // replace with valid value
                };
                smtp.Host = "smtp.gmail.com";
                smtp.EnableSsl = true;
                smtp.UseDefaultCredentials = true;
                smtp.Credentials = credential;
                smtp.Port = 587;
                smtp.Send(message);
                envio = true;
            }

            return envio;
        }

        [HttpPost]
        public ActionResult Guardar(SolicitudesModels solicitudesModels)
        {
            try
            {
                if (ModelState.ContainsKey("Solicitud.IdSolicitud"))
                    ModelState["Solicitud.IdSolicitud"].Errors.Clear();
                if (solicitudesModels.TipoTramite == (int)TipoTramite.DispTestamentaria)
                {
                    if (string.IsNullOrEmpty(solicitudesModels.Cujus))
                    {
                        ModelState.AddModelError("Cujus", "Debe llenar la información de nombre de Cujos (finado).");
                    }
                    if (string.IsNullOrEmpty(solicitudesModels.Juzgado))
                    {
                        ModelState.AddModelError("Juzgado", "Debe llenar la información de juzgado ó notaría que lo solicita.");
                    }
                }

                if (!ModelState.IsValid)
                {
                    ViewBag.TiposTramite = db.TiposTramites.ToList();
                    return View("Solicitud", solicitudesModels);
                }

                solicitudesModels.EstatusSolicitud = db.EstatusSolicitudes.Where(x => x.EstatusSolicitud.Contains("En revisión")).FirstOrDefault().IdEstatusSolicitud;
                solicitudesModels.FechaActualizacionEstatus = DateTime.Now;
                if (solicitudesModels.IdSolicitud.Equals(0))
                {
                    solicitudesModels.IdUserCreacion = User.Identity.GetUserId();
                    db.Solicitudes.Add(solicitudesModels);
                }
                else
                {
                    db.Entry(solicitudesModels).State = EntityState.Modified;
                }

                db.SaveChanges();
                if (!this.EnviarCorreoSolicitud(solicitudesModels.IdSolicitud))
                {
                    throw new Exception("No se pudo enviar correo de confirmación de solicitud.");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return RedirectToAction("Folio", new { id = solicitudesModels.IdSolicitud });
        }

        [HttpPost]
        public ActionResult SubirArchivo(HttpPostedFileBase file, int id)
        {
            if (file != null && file.ContentLength > 0)
            {
                // Extraemos el contenido en Bytes del archivo subido.
                var _contenido = new byte[file.ContentLength];
                file.InputStream.Read(_contenido, 0, file.ContentLength);

                // Separamos el Nombre del archivo de la Extensión.
                int indiceDelUltimoPunto = file.FileName.LastIndexOf('.');
                string _nombre = file.FileName.Substring(0, indiceDelUltimoPunto);
                string _extension = file.FileName.Substring(indiceDelUltimoPunto + 1,
                                    file.FileName.Length - indiceDelUltimoPunto - 1);

                // Instanciamos la clase Archivo y asignammos los valores.
                DocumentosModels _documento = new DocumentosModels()
                {
                    Nombre = _nombre,
                    Extension = _extension,
                    IdSolicitud = id
                };

                try
                {
                    db.Documentos.Add(_documento);
                    db.SaveChanges();
                    // Subimos el archivo al Servidor.
                    _documento.SubirArchivo(_contenido);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return RedirectToAction("Folio", new { id = id });
        }

        [HttpGet]
        public ActionResult DescargarArchivo(int id)
        {
            DocumentosModels _documento;
            FileContentResult _fileContent;

            using (db)
            {
                _documento = db.Documentos.FirstOrDefault(x => x.IdDocumento == id);
            }

            if (_documento == null)
            {
                return HttpNotFound();
            }
            else
            {
                try
                {
                    // Descargamos el archivo del Servidor.
                    _fileContent = new FileContentResult(_documento.DescargarArchivo(),
                                                         "application/octet-stream");

DGN21/Views/Solicitudes/Folio.cshtml
@model DGN21.Models.SolicitudesModels
@{
    ViewBag.Title = "Folio de Solicitud: " + Model.IdSolicitud;
    ViewBag.Message = "Adjunta documento(s) que acredite interés jurídico";
    if (User.IsInRole("ADMINISTRADOR"))
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }else if (User.IsInRole("RECEPCION"))
    {
        Layout = "~/Views/Shared/_LayoutRecepcion.cshtml";
    }else if (User.IsInRole("SECRETARIA(O)"))
    {
        Layout = "~/Views/Shared/_LayoutSecretaria.cshtml";
    }else if(User.IsInRole("ABOGADO(A)"))
    {
        Layout = "~/Views/Shared/_LayoutAbogado.cshtml";
    }else if (User.IsInRole("ARCHIVO"))
    {
        Layout = "~/Views/Shared/_LayoutArchivo.cshtml";
    }
}
@section Styles {
    <link href="//www.fuelcdn.com/fuelux/3.13.0/css/fuelux.min.css" rel="stylesheet">
}
<h2 class="alert alert-info">@ViewBag.Title</h2>
<div class="row">
    <div class="fuelux col-xs-12">
        @using (Html.BeginForm("SubirArchivo", "Solicitudes", new { id = Model.IdSolicitud }, FormMethod.Post, new { enctype = "multipart/form-data", method = "post" }))
        {
            <div class="wizard" data-initialize="wizard" id="myWizard">
                <div class="steps-container">
                    <ul class="steps">
                        <li data-step="1" class="active">
                            <span class="badge">1</span>@ViewBag.Message
                            <span class="chevron"></span>
                        </li>
                    </ul>
                </div>
                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="alert alert-danger">
                        @Html.ValidationSummary(false, "Fallas de documentos.", new { @class = "text-danger" })
                    </div>
                }
                <div class="step-content">
                    <div class="step-pane active sample-pane alert" data-step="1">
                        <div class="col-sm-6">
                            <input type="file" name="file" />
                        </div>
                        <div class="col-md-6 left">
                            <button type="submit" class="btn btn-sm btn-primary">
                                <span class="glyphicon glyphicon-open"></span>
                                &nbsp;Subir archivo
                            </button>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-12">
                                @foreach (var item in Model.Documentos)
                                {
                                    @*<a href="@Url.Action("DescargarArchivo", "Solicitudes", new { id = item.IdDocumento })">
                                        <span class="glyphicon glyphicon-save"></span>
                                        <span>@item.Nombre.@item.Extension</span>
                                    </a>
                                    <a href="@Url.Action("EliminarArchivo", "Solicitudes", new { id = item.IdDocumento })" class="text-danger">
                                        <span class="glyphicon glyphicon-remove text-danger small"></span>
                                        Eliminar archivo
                                    </a>*@
                                    <span class="glyphicon glyphicon-save-file"></span>
                                    <span>@item.Nombre.@item.Extension</span>
                                    <br />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@section Scripts {
    <script src="//www.fuelcdn.com/fuelux/3.13.0/js/fuelux.min.js"></script>
}

DGN21/Views/Solicitudes/InboxAsignada.cshtml
@model List<DGN21.Models.SolicitudesModels>
@{
    ViewBag.Title = "Bandeja de solicitudes ya asignadas";
    if(User.IsInRole("ADMINISTRADOR"))
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }else if (User.IsInRole("RECEPCION"))
    {
        Layout = "~/Views/Shared/_LayoutRecepcion.cshtml";
    }else if (User.IsInRole("SECRETARIA(O)"))
    {
        Layout = "~/Views/Shared/_LayoutSecretaria.cshtml";
    }else if (User.IsInRole("DIRECTOR(A)"))
    {
        Layout = "~/Views/Shared/_LayoutDirector.cshtml";
    }
    int dispTestamentaria = 4;
    int busquedaAnio = 5;
}
@section styles {
    <link rel="stylesheet" type="text/css" href="~/Content/DataTables/media/css/dataTables.bootstrap.css">
}
<h2>@ViewBag.Title</h2>
<br />
<div class="light-bordered-rigth">
    <div class="row">
        <div class="col-xs-12">
            <table id="datatable1" class="table table-striped table-bordered" style="width:100%;">
                <thead>
                    <tr>
                        <th style="text-align:center">FOLIO</th>
                        <th style="text-align:center">SOLICITANTE</th>
                        <th style="text-align:center">EMAIL</th>
                        <th style="text-align:center">TELEFONO</th>
                        <th style="text-align:center">TIPO DE TRAMITE</th>
                        <th style="text-align:center">FECHA DE SOLICITUD</th>
                        <th class="no-sort"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="text-align:center">
                                @Html.DisplayFor(modelItem => item.IdSolicitud)
                            </td>
                            <td>
                                @string.Format("{0} {1} {2}", item.NombreSolicitante, item.ApellidoPaterno, item.ApellidoMaterno)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CorreoElectronico)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefono)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TiposTramites.TipoTramite)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaCreacion)
                            </td>
                            <td>
                                <button id="detalle" type="button" class="btn btn-info btn-xs" title="Más información de solicitud" onclick="location.href='@Url.Action("Detalle", "Solicitudes", new { id = item.IdSolicitud })'">
                                    <i class="glyphicon glyphicon-info-sign"></i>
                                </button>
                                <br /><button id="solicitarBusqueda" type="button" class="btn btn-info btn-xs" title="Solicitar búsqueda por año" onclick="location.href='@Url.Action("SolicitarBusqueda", "Solicitudes", new { id = item.IdSolicitud })'">
                                    <i class="glyphicon glyphicon-search"></i> Solicitar búsqueda
                                </button>
                                @if (item.TipoTramite == dispTestamentaria || item.TipoTramite == busquedaAnio)
                                {
                                    <br /><button id="papeletaPago" type="button" class="btn btn-info btn-xs" title="Generar papeleta de pago" onclick="location.href='@Url.Action("PapeletaPagos", "Solicitudes", new { id = item.IdSolicitud })'">
                                        <i class="glyphicon glyphicon-file"></i> Papeleta de Pago
                                    </button>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.2/jspdf.plugin.autotable.js"></script>
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables/media/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables/media/js/dataTables.bootstrap.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable1').DataTable({
                "order": [[0, "desc"]],
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "Sin solicitudes",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Sin información",
                    "infoFiltered": "(Filtrado de _MAX_ registros totales)",
                    "paginate": {
                        "previous": "Anterior",
                        "next": "Siguiente",
                        "first": "Primera página",
                        "last": "Última página"
                    },
                    "sSearch": "Buscar:"
                },
                "columnDefs": [{
                    "targets": 'no-sort',
                    "orderable": false,
                }]
            });
        });
    </script>
}

DGN21/Views/Solicitudes/PapeletaPago.cshtml
@model DGN21.Models.ViewModels.SolicitudesViewModels
@{
    Layout = null;
    ViewBag.Title = "Papeleta de pago";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DGN21</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    <style>
        /* SOLUCIONA PROBLEMA DE SOLAPAMIENTO EN TABLAS <table /> */
        thead {
            display: table-header-group
        }

        tfoot {
            display: table-row-group
        }

        tr {
            page-break-inside: avoid
        }
    </style>
</head>
<body style="padding: 0px; margin: 0px; font-size: 16px;">
    <table class="table table-bordered align-middle" style="border: 1px double black;">
        <tr>
            <td>
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <img src="~/Content/img/logo_notarias.jpg" style="height: 100px;" />
                    </div>
                </div>
                <br />
                <br />
                <br />
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <strong>BOLETA DE PAGO POR COPIA SIMPLE</strong>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-xs-12 text-left">
                        CLAVE FISCAL: <strong> @Model.PapeletasPago.FormatosPapeletas.CveFiscal </strong>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-xs-12 text-right">
                        Hermosillo, Sonora; a ______ de _______________________ de @DateTime.Now.Year
                    </div>
                </div>
                <br />
                <br />
                <br />
                <div class="row">
                    <div class="col-xs-4 text-left">
                        <strong>
                            C. AGENTE FISCAL DEL ESTADO
                            <br />
                            P r e s e n t e.
                        </strong>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-xs-12 text-left">
                        Favor de recibir del portado la cantidad de $@Model.PapeletasPago.Cantidad (@Model.PapeletasPago.CantidadLetra 00/100 M.N.).
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 text-left">
                        Por concepto de pago de Derechos Notariales originados por <strong>@Model.PapeletasPago.FormatosPapeletas.Concepto</strong> de ESCRITURA: @Model.Solicitud.Escritura VOL: @Model.Solicitud.Vol Lic. @Model.Solicitud.Notario NP: @Model.Solicitud.NoNotaria de @Model.Solicitud.Demarcacion a solicitud de:
                        @string.Format("{0} {1} {2}", Model.Solicitud.NombreSolicitante, Model.Solicitud.ApellidoPaterno, Model.Solicitud.ApellidoMaterno).
                    </div>
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-xs-12 text-left">
                        <h5>
                            <small>
                                NOTA: LA AGENCIA FISCAL LES APLICARÁ EL 45% MÁS DE LOS COSTOS QUE CORRESPONDEN:
                                <br />DEL 15% PARA UNIVERSIDAD DE SONORA
                                <br />15% PARA INSFRAESTRUCTURA EDUCATIVA Y
                                <br />15% PARA EL CECOP
                            </small>
                        </h5>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <strong>
                            ATENDIÓ:
                            <br />
                            DIRECCIÓN GENERAL DE NOTARÍAS
                        </strong>
                    </div>
                </div>
                <br />
            </td>
        </tr>
    </table>
    <div class="row">
        <div class="col-xs-12 text-left">
            Una vez realizado el pago, se deberán digitalizar el comprobante de pago, y subirlo a la página <a href="http://tramitesdgn.sonora.gob.mx/" target="_blank" title="Trámites Dirección General de Notarias" class="acolor3">tramitesdgn.sonora.gob.mx</a> ingresando con su número de folio en Estatus de Solicitud.
        </div>
    </div>
</body>
</html>

DGN21/Views/Solicitudes/PapeletaPagos.cshtml
@model DGN21.Models.ViewModels.SolicitudesViewModels
@{
    ViewBag.Title = "Generar papeleta de pago";
    ViewBag.Message = "Información de papeleta de pago";
    if (User.IsInRole("ADMINISTRADOR"))
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    else if (User.IsInRole("RECEPCION"))
    {
        Layout = "~/Views/Shared/_LayoutRecepcion.cshtml";
    }
    else if (User.IsInRole("SECRETARIA(O)"))
    {
        Layout = "~/Views/Shared/_LayoutSecretaria.cshtml";
    }else if (User.IsInRole("DIRECTOR(A)"))
    {
        Layout = "~/Views/Shared/_LayoutDirector.cshtml";
    }
}
@section Styles {
    <link href="//www.fuelcdn.com/fuelux/3.13.0/css/fuelux.min.css" rel="stylesheet">
}
<h2>@ViewBag.Title</h2>
<h3 class="alert alert-info">
    INFORMACIÓN GENERAL DE SOLICITUD PREVIA<br />
    Folio solicitud: @Model.Solicitud.IdSolicitud<br />
    Estatus de solicitud: @Model.Solicitud.EstatusSolicitudes.EstatusSolicitud<br />
    Solicitante: @Model.Solicitud.NombreSolicitante @Model.Solicitud.ApellidoPaterno @Model.Solicitud.ApellidoMaterno<br />
    E-mail: @Model.Solicitud.CorreoElectronico<br />
    Cel: @Model.Solicitud.Telefono
</h3>
<br />
<div class="row">
    <div class="fuelux col-xs-12">
        <div class="wizard" data-initialize="wizard" id="myWizard">
            <div class="steps-container">
                <ul class="steps">
                    <li data-step="1" class="active">
                        <span class="badge">1</span>@ViewBag.Message
                        <span class="chevron"></span>
                    </li>
                </ul>
            </div>
            <div class="step-content">
                <div class="step-pane active sample-pane alert" data-step="1">
                    @using (Html.BeginForm("PapeletaPagos", "Solicitudes", FormMethod.Post, new { id = "frmPapeleta" }))
                    {
                        if (!ViewData.ModelState.IsValid)
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationSummary(false, "Debe ingresar toda la información requerida.", new { @class = "text-danger" })
                            </div>
                        }
                        <div class="row">
                            @Html.HiddenFor(model => model.Solicitud.IdSolicitud, new { @class = "form-control", @Id = "hdIdSolicitud" })
                            @Html.HiddenFor(model => model.PapeletasPago.IdPapeletaPago, new { @class = "form-control", @Id = "hdIdPapeletaPago" })
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PapeletasPago.FormatosPapeletas, new { @Id = "lblEstatus", @class = "control-label" })
                                    @Html.DropDownListFor(model => model.PapeletasPago.IdFormatoPapeleta, new SelectList(ViewBag.FormatosPapeletas, "IdFormatoPapeleta", "NombreFormato"), "Seleccione...", new { @class = "form-control", @Id = "ddlEstatus", @name = "ddlFormatos", @style = "width: 100%!important;" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PapeletasPago.Cantidad, new { @class = "control-label", @id = "lblCantidad" })
                                    @Html.TextBoxFor(model => model.PapeletasPago.Cantidad, new { @class = "form-control", @Id = "txtCantidad" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PapeletasPago.CantidadLetra, new { @class = "control-label", @id = "lblCantidadLetra" })
                                    @Html.TextBoxFor(model => model.PapeletasPago.CantidadLetra, new { @class = "form-control", @Id = "txtCantidadLetra" })
                                </div>
                            </div>
                        </div>
                        <div class="pull-right">
                            @if (Model.PapeletasPago != null && !Model.PapeletasPago.IdPapeletaPago.Equals(0))
                            {
                                <button id="papeletaPago" type="button" class="btn btn-info" onclick="location.href='@Url.Action("DownloadPapeletaPago", "Solicitudes", new { id = Model.PapeletasPago.IdSolicitud })'">
                                    <i class="glyphicon glyphicon-download"></i> Papeleta de pago
                                </button>
                            }
                            <button type="submit" class="btn btn-success">
                                <i class="glyphicon glyphicon-floppy-save"></i> Guardar
                            </button>
                        </div>
                    }
                    @{Html.EndForm();}
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="//www.fuelcdn.com/fuelux/3.13.0/js/fuelux.min.js"></script>
}